import React, {useState} from "react"
import axios from "axios"
import Link from "next/link"
import { useRouter } from "next/router"
import {AiOutlineMenu, AiOutlineClose} from 'react-icons/ai'
import toast from "react-hot-toast"
import { useUserContext } from "../../contexts/userContext"
import { API_URL } from "../../utils/variables"
import Head from "next/head"

const Header = () => {
    const {user, loaded, setUser, setLoaded} = useUserContext()
    const router = useRouter()
    const logOut = () => {
        if(loaded) {
            axios.post(`${API_URL}/auth/logout`, null, {withCredentials: true}).then(() => {
                setUser(null)
                router.push('/').then(() => toast.success('You has been logged out with successfully'))
            })
        }
    }
    const [menu, setMenu] = useState<boolean>(false)
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className='w-full z-[999]'>
                <nav role='main-navigation' className='fixed left-0 w-full flex items-center justify-between px-10 md:px-24 py-7 bg-black shadow-md'>
                    <Link href='/'>
                        <h1 className='font-semibold text-xl text-white cursor-pointer duration-200 hover:scale-105 hover:text-blue-500'>Curs</h1>
                    </Link>
                    {
                        menu ? <AiOutlineClose className='text-white text-xl cursor-pointer font-extrabold md:hidden' onClick={() => setMenu(false)} /> : <AiOutlineMenu className='text-white text-xl cursor-pointer font-extrabold md:hidden' onClick={() => setMenu(true)} />
                    }
                    <div className={`absolute top-[84px] left-0 w-full flex justify-center md:justify-start duration-300 bg-black py-10 ${menu ? 'translate-x-0' : 'translate-x-[200%]'} md:relative md:top-0 md:w-auto md:bg-transparent md:py-0 md:translate-x-0 md:duration-0`}>
                        {
                            loaded && user ?
                                <ul className='list-none flex flex-col md:flex-row gap-2 w-full md:w-auto justify-center md:justify-start flex-wrap items-center '>
                                    <li>
                                        <Link href={`/profile/${user.id}`}>
                                            <a className={`text-white font-medium text-lg md:text-base duration-200 hover:text-blue-500 hover:border-b-2 hover:border-b-blue-500 ${router.pathname.includes('/profile') ? 'text-blue-500 border-b-2 border-b-blue-500' : ''}`}>My profile</a>
                                        </Link>
                                    </li>
                                    <li>
                                        <Link href='/courses'>
                                            <a className={`text-white font-medium text-lg md:text-base duration-200 hover:text-blue-500 hover:border-b-2 hover:border-b-blue-500 ${router.pathname === '/courses' ? 'text-blue-500 border-b-2 border-b-blue-500' : ''}`}>My courses</a>
                                        </Link>
                                    </li>
                                    <li>
                                        <span onClick={logOut} className='text-white font-medium text-lg md:text-base cursor-pointer duration-200 hover:text-blue-500 hover:border-b-2 hover:border-b-blue-500'>
                                            Logout
                                        </span>
                                    </li>
                                </ul>
                            :
                                <Link href='/'>
                                    <a className='text-white font-medium text-lg md:text-base mx-auto duration-200 w-full text-center hover:text-blue-500 hover:border-b-2 hover:border-b-blue-500'>Login</a>
                                </Link>
                        }
                    </div>
                </nav>
            </header>
        </>
    )
}

export default Header